spring:
  cloud:
    compatibility-verifier:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    codecs:
      max-in-memory-size: 500MB

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

nexgen:
  jasper:
    uri: http://jasperreports:8080
    admin-user: jasperadmin
    admin-password: jasperadmin
    formio-user: jasperadmin
    formio-password: jasperadmin